# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = 'bento/centos-7.2'
BOX_VERSION = '2.2.9'

Vagrant.configure("2") do |config|
  
  config.vm.define 'web1' do |node|
    node.vm.hostname = 'web1' 
    node.vm.box = BOX
    node.vm.box_version = BOX_VERSION
    node.vm.network "private_network", ip: '192.168.10.43'
    node.vm.provision :shell, path: 'bootstrap.sh'
  end

  config.vm.define 'web2' do |node|
    node.vm.hostname = 'web2' 
    node.vm.box = BOX
    node.vm.box_version = BOX_VERSION
    node.vm.network "private_network", ip: '192.168.10.44'
    node.vm.provision :shell, path: 'bootstrap.sh'
  end

  config.vm.define 'lb01' do |node|
    node.vm.hostname = 'lb01' 
    node.vm.box = BOX
    node.vm.box_version = BOX_VERSION
    node.vm.network "forwarded_port", guest: 80, host: 9000
    node.vm.provision :shell, path: 'bootstrap.sh'
  end

end
